stages:
  - configure
  - lint
  - build
  - test
  - documentation
  - package


before_script:
  - apt-get update
  - apt-get install -y ghc cabal-install
  - cabal update


configure:cabal:
  stage: configure
  image: debian:stable
  script:
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests
    - cabal configure --enable-tests
  artifacts:
    paths:
      - '.cabal-sandbox/'
      - 'dist/'


build:cabal:
  stage: build
  image: debian:stable
  script:
    - cabal build
  dependencies:
    - configure:cabal
  artifacts:
    paths:
      - '.cabal-sandbox/'
      - 'dist/'


test:cabal:
  stage: test
  image: debian:stable
  script:
    - cabal test --test-options "--pattern !/skip/"
  dependencies:
    - build:cabal
